inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

  DisplayCopNames: true
  Exclude:
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  AllowPredicates: true

Metrics/BlockLength:
  Exclude:
    - 'benchmark/setup_db.rb'
    - '**/*.rake'
    - 'spec/spec_helper.rb'
    - 'spec/**/*_spec.rb'
