inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

  DisplayCopNames: true
  Exclude:
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    # Suppress errors on RuboCop 0.50.0 & Ruby 3.1+
    - 'lib/mysql2/console.rb'
    - 'tasks/generate.rake'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  AllowPredicates: true
