inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 1.9

  DisplayCopNames: true
  Exclude:
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrivialAccessors:
  AllowPredicates: true
