---
version: "{build}"
clone_depth: 10
install:
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install --without benchmarks --path vendor/bundle
  - IF DEFINED MINGW_PACKAGE_PREFIX (ridk exec pacman -S --noconfirm --needed %MINGW_PACKAGE_PREFIX%-libmariadbclient)
build_script:
  - bundle exec rake compile
test_script:
  - '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" --version'
  - >
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -p"Password12!" -e "
    CREATE DATABASE IF NOT EXISTS test;
    CREATE USER '%USERNAME%'@'localhost';
    SET PASSWORD = PASSWORD('');
    FLUSH PRIVILEGES;
    "
  - bundle exec rake spec
on_failure:
  - find tmp -name "*.log" | xargs cat
environment:
  matrix:
    - ruby_version: "26-x64"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
    - ruby_version: "25-x64"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
    - ruby_version: "24-x64"
      MINGW_PACKAGE_PREFIX: "mingw-w64-x86_64"
    - ruby_version: "24"
      MINGW_PACKAGE_PREFIX: "mingw-w64-i686"
    - ruby_version: "23-x64"
    - ruby_version: "23"
    - ruby_version: "22-x64"
    - ruby_version: "22"
    - ruby_version: "21-x64"
    - ruby_version: "21"
    - ruby_version: "200-x64"
    - ruby_version: "200"
cache:
  - vendor
services:
  - mysql
hosts:
  mysql2gem.example.com: 127.0.0.1
