ARG IMAGE=fedora:39
FROM ${IMAGE}

WORKDIR /build
COPY . .

RUN cat /etc/fedora-release
RUN dnf -yq update
# The options are to install faster.
RUN dnf -yq install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  gcc \
  gcc-c++ \
  git \
  libyaml-devel \
  make \
  redhat-rpm-config \
  ruby-devel \
  rubygem-bigdecimal \
  rubygem-bundler \
  rubygem-json

RUN rpm -ivh https://dev.mysql.com/get/mysql80-community-release-fc39-2.noarch.rpm && \
    yum --enablerepo=mysql80-community install -y mysql-community-devel mysql-community-common mysql-community-server mysql-community-client

CMD bash ci/container.sh
